### ISSUE TITLE
Information on TimeSeries adaptation

### ISSUE THREAD

**Issue by Piffo** [Aiwiscal/ECG_UNet#1]
Hi @Aiwiscal ,
I'm here to ask to you a question about your approach: where and how you adapt the models take "off the shelfs" (this oneshttps://github.com/divamgupta/image-segmentation-keras) for using it with Time series?

Thanks in advance.
Cheers,
Michele

**Comment by Aiwiscal** [comment]
Hi. No "off the shelfs" model was used in this project. I trained the model(1-D version of U-Net) from scratch using ECGs.
